trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Dependencies"

  - script: |
      npm install
      npm run cy:azure
    displayName: "Run Cypress Test"
