version: '3'
services:

  cypress:
    image: cypress/browsers:node14.15.0-chrome86-ff82
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cypress
    command: npx cypress run cy:ci
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.json:/app/cypress.json
    privileged: true
    ipc: host
    shm_size: 1024M  