name: CypressCI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.15.0-chrome86-ff82

    steps:
      - uses: actions/checkout@v1
      - name: npm install and build
        run: |
          npm install
      - name: Cypress.io
        uses: cypress-io/github-action@v2.6.1
        with:
          # command: "cypress run --spec 'cypress/integration/example_spec.js' --record --key=${{ secrets.CYPRESS_TOKEN }}"
          spec: cypress/integration/example_spec.js