name: CypressCI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.16.0-chrome90-ff88

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x' 
      - name: Install dependencies
        run: |
          npm install -g cy2
          npm install
      - name: Checkout tools repo
      - uses: actions/checkout@v2
        with:
          repository: dipjyotimetia/ExpenseWeb
          path: ExpenseWeb

      - name: Install dependencies
        run: |
          npm install -g cy2
          npm install
      - name: Setup Aplication under test
        run: docker-compose -f ExpenseWeb/docker-compose.yml up -d

      - name: Setup Sorry Cypress Environment
        run: docker-compose up -d

      - name: Cypress & Percy visual test
        # uses: cypress-io/github-action@v2.9.12
        # with:
        #   # command: "cypress run --spec 'cypress/integration/example_spec.js' --record --key=${{ secrets.CYPRESS_TOKEN }}"
        #   spec: cypress/integration/example_spec.ts
        uses: percy/exec-action@v0.3.1
        with:
          custom-command: "npm test"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
