name: CypressCI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.18.0-chrome83-ff77

    steps:
      - uses: actions/checkout@v1
      - name: npm install and build
        run: |
          npm install
      - name: Visual Testing
        uses: percy/exec-action@v0.3.0
        with:
          # command: "cypress run --spec 'cypress/integration/example_spec.js' --record --key=${{ secrets.CYPRESS_TOKEN }}"
          command: "cypress run --spec 'cypress/integration/example_spec.js'"
        env:
          CI: true
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}