name: CypressCI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.16.0-chrome90-ff88

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          npm install
      - name: Cypress & Percy visual test
      - uses: cypress-io/github-action@v2.9.12
        with:
          command: "cypress run --spec 'cypress/integration/example_spec.js' --record --key=${{ secrets.CYPRESS_TOKEN }}"
          # spec: cypress/integration/example_spec.ts
      - uses: percy/exec-action@v0.3.1
        with:
          custom-command: "npm test"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
