name: CypressCI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73

    steps:
      - uses: actions/checkout@v1
      - name: npm install and build
        run: |
          npm install
      - name: Visual Testing
        uses: percy/exec-action@v0.3.0
        with:
          command: "cypress run --spec 'cypress/integration/example_spec.js' --record --key=1f71b8c4-b038-49b9-b027-807293886a02"
        env:
          CI: true
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}