name: CypressCI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.16.0-chrome90-ff88

    steps:
      - uses: actions/checkout@v1
      - name: npm install and test
        run: |
          npm install
      - name: Cypress & Percy visual test
        # uses: cypress-io/github-action@v2.9.12
        # with:
        #   # command: "cypress run --spec 'cypress/integration/example_spec.js' --record --key=${{ secrets.CYPRESS_TOKEN }}"
        #   spec: cypress/integration/example_spec.ts
        uses: percy/exec-action@v0.3.1
        with:
          custom-command: "npm test"
      - name: Run in BrowserStack    
        run: |
          BUILD_ID=$(browserstack-cypress run --sync --username $BROWSERSTACK_USER --key $BROWSERSTACK_PASS | grep 'build id:' | rev | cut -d" " -f1 | rev)
          # Or, you can read this from the log/build_results.txt file as well
          # Say, it takes around 60 seconds on an average to finish your tests
          # You can wait for 60 seconds, and then start polling for build status every 10 seconds
          BUILD_TIME_AVG=60
          POLLING_INTERVAL=10
          BUILD_STATUS="running"

          $(sleep $BUILD_TIME_AVG)

          while [ $BUILD_STATUS == "running" ]
          do
            # Get the build status
            $(browserstack-cypress build-info $BUILD_ID > temp.txt)
            BUILD_STATUS=$(awk '/"status":/ {print $2} ' temp.txt | head -n1 | cut -d"," -f1 | cut -d"\"" -f2)
            $(rm temp.txt)

            # Sleep until next poll
            $(sleep $POLLING_INTERVAL)
          done
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          BROWSERSTACK_USER: ${{BROWSERSTACK_USER}}
          BROWSERSTACK_PASS: ${{BROWSERSTACK_PASS}}
