name: CypressCI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73

    steps:
      - uses: actions/checkout@v1
      - name: npm install and build
        run: |
          npm install
      - name: Visual Testing
        uses: percy/exec-action@v0.3.0
        with:
          command: "cypress run --spec 'cypress/integration/example_spec.js' --record --key=d47b182e-a843-40f4-b6ff-89827696ed8a --parallel"
        env:
          CI: true
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}